/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DelesteFanCalculator;

import org.junit.Test;

import DelesteFanCalculator.Lib.Calculation;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        System.out.println(Calculation.fan(1000000, 100, 100, 100, 100));
    }
}
