/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DelesteFanCalculator;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

import DelesteFanCalculator.Lib.Calculation;

public class DelesteFanCalculator extends JFrame {

    private JPanel contentPane;
	private JLabel labelTest;
	private JButton btnCalc;
	private JTextField fieldScore;
	private JPanel panel;
	private JTextField fieldRoom;
	private JLabel labelRoom;
	private JTextField fieldCentre;
	private JTextField fieldProduce;
	private JLabel labelCentre;
	private JLabel labelProduce;
	private JLabel labelPremium;
	private JTextField fieldPremium;
	private JCheckBox chkTwice;

	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					DelesteFanCalculator frame = new DelesteFanCalculator();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

    
	public DelesteFanCalculator() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 640, 360);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new BorderLayout(0, 0));
		setContentPane(contentPane);

		labelTest = new JLabel("Simulated fan number here.");
		contentPane.add(labelTest, BorderLayout.CENTER);

		btnCalc = new JButton("Start Calculating");
		btnCalc.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int score = Integer.parseInt(fieldScore.getText());
				int room = Integer.parseInt(fieldRoom.getText());
				int center = Integer.parseInt(fieldCentre.getText());
				int produce = Integer.parseInt(fieldProduce.getText());
				int premium = Integer.parseInt(fieldPremium.getText());
				int fan = Calculation.fan(score, room, center, produce, premium);
				if(chkTwice.isSelected())
					fan = fan * 2;
				labelTest.setText(String.valueOf(fan));
			}
		});
		contentPane.add(btnCalc, BorderLayout.SOUTH);

		fieldScore = new JTextField();
		contentPane.add(fieldScore, BorderLayout.NORTH);
		fieldScore.setColumns(10);

		panel = new JPanel();
		contentPane.add(panel, BorderLayout.EAST);
		GridBagLayout gbl_panel = new GridBagLayout();
		gbl_panel.columnWidths = new int[] {55, 52};
		gbl_panel.rowHeights = new int[] {122, 20, 30, 0, 0, 0};
		gbl_panel.columnWeights = new double[]{1.0, 1.0};
		gbl_panel.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		panel.setLayout(gbl_panel);

								labelRoom = new JLabel("Room");
								GridBagConstraints gbc_labelRoom = new GridBagConstraints();
								gbc_labelRoom.insets = new Insets(0, 0, 5, 5);
								gbc_labelRoom.gridx = 0;
								gbc_labelRoom.gridy = 1;
								panel.add(labelRoom, gbc_labelRoom);

						fieldRoom = new JTextField();
						GridBagConstraints gbc_fieldRoom = new GridBagConstraints();
						gbc_fieldRoom.insets = new Insets(0, 0, 5, 0);
						gbc_fieldRoom.gridx = 1;
						gbc_fieldRoom.gridy = 1;
						panel.add(fieldRoom, gbc_fieldRoom);
						fieldRoom.setColumns(10);

				labelCentre = new JLabel("Center");
				GridBagConstraints gbc_labelCentre = new GridBagConstraints();
				gbc_labelCentre.insets = new Insets(0, 0, 5, 5);
				gbc_labelCentre.gridx = 0;
				gbc_labelCentre.gridy = 2;
				panel.add(labelCentre, gbc_labelCentre);

		fieldCentre = new JTextField();
		GridBagConstraints gbc_fieldCentre = new GridBagConstraints();
		gbc_fieldCentre.insets = new Insets(0, 0, 5, 0);
		gbc_fieldCentre.fill = GridBagConstraints.HORIZONTAL;
		gbc_fieldCentre.gridx = 1;
		gbc_fieldCentre.gridy = 2;
		panel.add(fieldCentre, gbc_fieldCentre);
		fieldCentre.setColumns(10);

				labelProduce = new JLabel("Produce");
				GridBagConstraints gbc_labelProduce = new GridBagConstraints();
				gbc_labelProduce.insets = new Insets(0, 0, 5, 5);
				gbc_labelProduce.anchor = GridBagConstraints.NORTH;
				gbc_labelProduce.gridx = 0;
				gbc_labelProduce.gridy = 3;
				panel.add(labelProduce, gbc_labelProduce);

		fieldProduce = new JTextField();
		GridBagConstraints gbc_fieldProduce = new GridBagConstraints();
		gbc_fieldProduce.insets = new Insets(0, 0, 5, 0);
		gbc_fieldProduce.fill = GridBagConstraints.HORIZONTAL;
		gbc_fieldProduce.gridx = 1;
		gbc_fieldProduce.gridy = 3;
		panel.add(fieldProduce, gbc_fieldProduce);
		fieldProduce.setColumns(10);

		labelPremium = new JLabel("PremiumPass");
		GridBagConstraints gbc_labelPremium = new GridBagConstraints();
		gbc_labelPremium.insets = new Insets(0, 0, 5, 5);
		gbc_labelPremium.gridx = 0;
		gbc_labelPremium.gridy = 4;
		panel.add(labelPremium, gbc_labelPremium);

		fieldPremium = new JTextField();
		GridBagConstraints gbc_fieldPremium = new GridBagConstraints();
		gbc_fieldPremium.insets = new Insets(0, 0, 5, 0);
		gbc_fieldPremium.fill = GridBagConstraints.HORIZONTAL;
		gbc_fieldPremium.gridx = 1;
		gbc_fieldPremium.gridy = 4;
		panel.add(fieldPremium, gbc_fieldPremium);
		fieldPremium.setColumns(10);

		chkTwice = new JCheckBox("ファン数2倍期間");
		GridBagConstraints gbc_chkTwice = new GridBagConstraints();
		gbc_chkTwice.gridx = 1;
		gbc_chkTwice.gridy = 5;
		panel.add(chkTwice, gbc_chkTwice);
	}


}
